spring:
  application:
    name: EcomCartManagementSystem
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host:
      port:
      username:
      password:
      ssl:
        enabled: true
  datasource:
    url:
    username:
    password:
  flyway:
    baseline-on-migrate: true
server:
  port: 8282