spring:
  application:
    name: EcomCartManagementSystem
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cache:
    type: redis
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org:
      springframework:
        data:
          redis: info
springdoc:
  override-with-generic-response: true
  api-docs:
    path: /api-docs